/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AttemptedKnowledgeGap,  ExtractedFact,  FollowUpQueryGeneration,  GenerateQueryArgs,  KnowledgeGapAnalysis,  KnowledgeGapHistory,  Message,  Query,  QueryGenerationState,  Reflection,  ReflectionState,  SearchQueryList,  SearchResult,  SearchStateOutput,  WebSearchState } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface AttemptedKnowledgeGap {
        description?: (string | null)
        attemptCount?: (number | null)
        status?: ("active" | "abandoned" | "resolved" | null)
        previousQueries?: (string | null)[]
        relatedQuestionIds?: (number | null)[]
        firstAttemptedRound?: (number | null)
        lastAttemptedRound?: (number | null)
    }
    
    export interface ExtractedFact {
        sourceId?: (string | null)
        relevantFacts?: (string | null)[]
        summary?: (string | null)
    }
    
    export interface FollowUpQueryGeneration {
        queries?: (string | null)[]
        rationale?: (string | null)
        queryStrategy?: (string | null)
    }
    
    export interface GenerateQueryArgs {
        research_topic?: (string | null)
        current_date?: (string | null)
        number_queries: ((number | null) | null)
    }
    
    export interface KnowledgeGapAnalysis {
        shouldContinueResearch?: (boolean | null)
        nextGapToResearch: ((string | null) | null)
        gapStatus?: ("new" | "continuing" | "switching" | "complete" | null)
        reasoning?: (string | null)
        updatedGapHistory?: (partial_types.AttemptedKnowledgeGap | null)[]
    }
    
    export interface KnowledgeGapHistory {
        gaps?: (partial_types.AttemptedKnowledgeGap | null)[]
        currentGapIndex: ((number | null) | null)
    }
    
    export interface Message {
        role?: (string | null)
        content?: (string | null)
    }
    
    export interface Query {
        query?: (string | null)
        rationale?: (string | null)
    }
    
    export interface QueryGenerationState {
        search_query?: (partial_types.Query | null)[]
    }
    
    export interface Reflection {
        isSufficient?: (boolean | null)
        answeredQuestions?: (number | null)[]
        unansweredQuestions?: (number | null)[]
        relevantSummaryIds?: (string | null)[]
        currentGapClosed?: (boolean | null)
        newGapsIdentified: ((string | null)[] | null)
    }
    
    export interface ReflectionState {
        is_sufficient?: (boolean | null)
        knowledge_gap?: (string | null)
        follow_up_queries?: (string | null)[]
        research_loop_count?: (number | null)
        number_of_ran_queries?: (number | null)
    }
    
    export interface SearchQueryList {
        queryPlan?: (string | null)[]
        query?: (string | null)[]
        rationale?: (string | null)
    }
    
    export interface SearchResult {
        url?: (string | null)
        id?: (string | null)
        title?: (((string | null) | null) | ((null | null) | null) | null)
        highlights?: (string | null)[]
        highlightScores?: (number | null)[]
        text?: (string | null)
    }
    
    export interface SearchStateOutput {
        running_summary: ((string | null) | null)
    }
    
    export interface WebSearchState {
        search_query?: (string | null)
        id?: (string | null)
    }
    
}